/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.servicios.ServicioCuenta;
import java.util.ArrayList;
import java.util.List;
import modelo.Cuenta;
import modelo.CuentasListar;
import vista.modeloTablas.ModeloTablaCuentas;

/**
 *
 * @author macbookpro
 */
public class ListaCuentasUsuario extends javax.swing.JInternalFrame {
    private ServicioCuenta sc;
    private List<Cuenta> lista_cuentas;
    private ModeloTablaCuentas modelo_activas;
    private ModeloTablaCuentas modelo_inactivas;
    
    /**
     * Creates new form ListaCuentasUsuario
     */
    public ListaCuentasUsuario() {
        this.sc = new ServicioCuenta();
        this.lista_cuentas = new ArrayList<Cuenta>();
        this.modelo_activas = new ModeloTablaCuentas();
        this.modelo_inactivas = new ModeloTablaCuentas();
        initComponents();
        cargarTabla();
    }
    
    public void cargarTabla(){
        this.lista_cuentas = this.sc.listar();
        List <Cuenta> cuentas_activas = new ArrayList<Cuenta>();
        List <Cuenta> cuentas_inactivas = new ArrayList<Cuenta>();
        List <CuentasListar> lista_activas_orden = new ArrayList<CuentasListar>();
        List <CuentasListar> lista_inactivas_orden = new ArrayList<CuentasListar>();
        
        for (int i = 0; i < this.lista_cuentas.size(); i++) {
            if (this.lista_cuentas.get(i).isEstado_usuario()) {
                cuentas_activas.add(lista_cuentas.get(i));
            }else{
                cuentas_inactivas.add(lista_cuentas.get(i));
            }
        }
        CuentasListar c;
        for (int i = 0; i < cuentas_activas.size(); i++) {
            c = new CuentasListar();
            c.setOrden(i+1);
            c.setObj_cuenta(cuentas_activas.get(i));
            lista_activas_orden.add(c);
        }
        
        CuentasListar c1;
        for (int i = 0; i < cuentas_inactivas.size(); i++) {
            c1 = new CuentasListar();
            c1.setOrden(i+1);
            c1.setObj_cuenta(cuentas_inactivas.get(i));
            lista_inactivas_orden.add(c1);
        }
        
        
        this.modelo_activas.setLista(lista_activas_orden);
        this.modelo_inactivas.setLista(lista_inactivas_orden);
        this.tablaCuentasUsuario.setModel(this.modelo_activas);
        this.tabla_cuentas_inactivas.setModel(this.modelo_inactivas);
        this.tablaCuentasUsuario.updateUI();
        this.tabla_cuentas_inactivas.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCuentasUsuario = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_cuentas_inactivas = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista Cuentas de Usuario"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        tablaCuentasUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaCuentasUsuario);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton1.setText("Nuevo");

        jButton2.setText("Editar");

        jButton3.setText("Eliminar");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("CUENTAS INACTIVAS"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        tabla_cuentas_inactivas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tabla_cuentas_inactivas);

        jPanel2.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablaCuentasUsuario;
    private javax.swing.JTable tabla_cuentas_inactivas;
    // End of variables declaration//GEN-END:variables
}
