/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.image.BufferedImage;
import java.io.InputStream;
import javax.imageio.ImageIO;

/**
 *
 * @author anderson
 */
public class VistaPrincipal extends javax.swing.JFrame {

    // poner imanen de fondo
    public InputStream fondo = this.getClass()
            .getResourceAsStream("/vista/imagenes/fondo.jpg");
    
    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        // llamamos a la funcion para q se cargue el fondo
        cargar_imagen(obj_escritorio_jDesktopPane, fondo);
        this.setVisible(true);
        
    }
    
    // cargamos imagen
    public void cargar_imagen(javax.swing.JDesktopPane escritorio, InputStream imagen){
        try {
            BufferedImage image = ImageIO.read(imagen);
            escritorio.setBorder(new Fondo(image));
        } catch (Exception e) {
            System.out.println("No encuentra imagen");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        obj_escritorio_jDesktopPane = new javax.swing.JDesktopPane();
        menuPrincipal_jMenuBar1 = new javax.swing.JMenuBar();
        archivo_jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        cliente_jMenu2 = new javax.swing.JMenu();
        nuevoCliente_jMenuItem3 = new javax.swing.JMenuItem();
        listarCliente_jMenuItem4 = new javax.swing.JMenuItem();
        producto_jMenu3 = new javax.swing.JMenu();
        nuevoProducto_jMenuItem5 = new javax.swing.JMenuItem();
        listarProducto_jMenuItem6 = new javax.swing.JMenuItem();
        venta_jMenu4 = new javax.swing.JMenu();
        usuario_jMenu5 = new javax.swing.JMenu();
        nuevoUsuario_jMenuItem2 = new javax.swing.JMenuItem();
        compra_jMenu6 = new javax.swing.JMenu();
        proveedor_jMenu2 = new javax.swing.JMenu();
        ayuda_jMenu7 = new javax.swing.JMenu();
        manual_jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(obj_escritorio_jDesktopPane, java.awt.BorderLayout.CENTER);

        archivo_jMenu1.setText("Archivo");

        jMenuItem1.setText("Salir");
        archivo_jMenu1.add(jMenuItem1);

        menuPrincipal_jMenuBar1.add(archivo_jMenu1);

        cliente_jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/Clientes people.png"))); // NOI18N
        cliente_jMenu2.setText("Clientes");

        nuevoCliente_jMenuItem3.setText("Nuevo Cliente");
        nuevoCliente_jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoCliente_jMenuItem3ActionPerformed(evt);
            }
        });
        cliente_jMenu2.add(nuevoCliente_jMenuItem3);

        listarCliente_jMenuItem4.setText("Listar Clientes");
        listarCliente_jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarCliente_jMenuItem4ActionPerformed(evt);
            }
        });
        cliente_jMenu2.add(listarCliente_jMenuItem4);

        menuPrincipal_jMenuBar1.add(cliente_jMenu2);

        producto_jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/producto.png"))); // NOI18N
        producto_jMenu3.setText("Productos");

        nuevoProducto_jMenuItem5.setText("Nuevo Producto");
        producto_jMenu3.add(nuevoProducto_jMenuItem5);

        listarProducto_jMenuItem6.setText("Listar Productos");
        producto_jMenu3.add(listarProducto_jMenuItem6);

        menuPrincipal_jMenuBar1.add(producto_jMenu3);

        venta_jMenu4.setText("Ventas");
        menuPrincipal_jMenuBar1.add(venta_jMenu4);

        usuario_jMenu5.setText("Usuarios");

        nuevoUsuario_jMenuItem2.setText("jMenuItem2");
        nuevoUsuario_jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoUsuario_jMenuItem2ActionPerformed(evt);
            }
        });
        usuario_jMenu5.add(nuevoUsuario_jMenuItem2);

        menuPrincipal_jMenuBar1.add(usuario_jMenu5);

        compra_jMenu6.setText("Compras");
        menuPrincipal_jMenuBar1.add(compra_jMenu6);

        proveedor_jMenu2.setText("Proveedores");
        menuPrincipal_jMenuBar1.add(proveedor_jMenu2);

        ayuda_jMenu7.setText("Ayuda");

        manual_jMenuItem7.setText("Manual");
        manual_jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manual_jMenuItem7ActionPerformed(evt);
            }
        });
        ayuda_jMenu7.add(manual_jMenuItem7);

        menuPrincipal_jMenuBar1.add(ayuda_jMenu7);

        setJMenuBar(menuPrincipal_jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoCliente_jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoCliente_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        NuevoCliente_JInternalFrame ventana = new NuevoCliente_JInternalFrame();
        obj_escritorio_jDesktopPane.add(ventana);
        ventana.show();
    }//GEN-LAST:event_nuevoCliente_jMenuItem3ActionPerformed

    private void nuevoUsuario_jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoUsuario_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nuevoUsuario_jMenuItem2ActionPerformed

    private void manual_jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manual_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manual_jMenuItem7ActionPerformed

    private void listarCliente_jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarCliente_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        listar_clientes_JInternalFrame ventana = new listar_clientes_JInternalFrame();
        obj_escritorio_jDesktopPane.add(ventana);
        ventana.show();
    }//GEN-LAST:event_listarCliente_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu archivo_jMenu1;
    private javax.swing.JMenu ayuda_jMenu7;
    private javax.swing.JMenu cliente_jMenu2;
    private javax.swing.JMenu compra_jMenu6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem listarCliente_jMenuItem4;
    private javax.swing.JMenuItem listarProducto_jMenuItem6;
    private javax.swing.JMenuItem manual_jMenuItem7;
    private javax.swing.JMenuBar menuPrincipal_jMenuBar1;
    private javax.swing.JMenuItem nuevoCliente_jMenuItem3;
    private javax.swing.JMenuItem nuevoProducto_jMenuItem5;
    private javax.swing.JMenuItem nuevoUsuario_jMenuItem2;
    private javax.swing.JDesktopPane obj_escritorio_jDesktopPane;
    private javax.swing.JMenu producto_jMenu3;
    private javax.swing.JMenu proveedor_jMenu2;
    private javax.swing.JMenu usuario_jMenu5;
    private javax.swing.JMenu venta_jMenu4;
    // End of variables declaration//GEN-END:variables
}
